# Generated by Django 4.2.2 on 2023-07-24 14:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
