# Generated by Django 4.2.2 on 2023-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0002_properties_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='fans',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='no_rooms',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
