# Generated by Django 4.2.2 on 2023-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0003_properties_fans_properties_no_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
