# Generated by Django 4.2.2 on 2023-07-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0004_properties_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('stars', models.CharField(max_length=2)),
            ],
        ),
    ]
