# Generated by Django 4.2.2 on 2023-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='stars',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='review',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
