# Generated by Django 4.2.2 on 2023-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0006_remove_feedback_message_remove_feedback_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='review',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
        migrations.AddField(
            model_name='feedback',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='property',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
