# Generated by Django 4.2.2 on 2023-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0007_remove_feedback_rating_remove_feedback_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('property', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
