# Generated by Django 4.2.3 on 2023-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0008_property_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='property/%y/%m/%d/'),
        ),
    ]
