# Generated by Django 4.2.3 on 2023-07-27 10:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0009_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='desc', unique=True),
        ),
    ]
