# Generated by Django 4.2.3 on 2023-07-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0011_alter_properties_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='Review',
        ),
    ]
