# Generated by Django 5.0.1 on 2024-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreview',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newreview',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
